package ua.artcode.week5;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Created by Yaroslav on 21.12.2014.
 */

@MappedSuperclass
public class AutoGeneratedIdentify {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    private int id;

    public AutoGeneratedIdentify() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
