package ua.artcode.week5;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by Yaroslav on 21.12.2014.
 */
@Entity
@Table(name = "Agencys")
public class PublishAgency extends AutoGeneratedIdentify {
    private String name;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.LAZY, mappedBy = "agency")
    private List<Author> authors = new ArrayList<>();

    public PublishAgency() {
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Author> getAuthors() {
        return authors;
    }

    public void setAuthors(List<Author> authors) {
        this.authors = authors;
    }
}
