package mountin.JPA;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Created by mountin on 21/12/2014.
 */
@MappedSuperclass
public class AutoGeneratedIndety {
@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)
    private int id;

}
