package mountin.JPA;

import org.hibernate.metamodel.binding.CascadeType;

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Created by mountin on 21/12/2014.
 */
@Entity
@Table(name= "BOOKS")
public class Book extends AutoGeneratedIndety{

    private String name;

    private int paper;

    @Transient
    private int integerId;

    @OneToOne(cascade = javax.persistence.CascadeType.PERSIST)
    private Author author;

    public Book(String name, int paper, int integerId, Author author) {
        this.name = name;
        this.paper = paper;
        this.integerId = integerId;
        this.author = author;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPaper() {
        return paper;
    }

    public void setPaper(int paper) {
        this.paper = paper;
    }

    public int getIntegerId() {
        return integerId;
    }

    public void setIntegerId(int integerId) {
        this.integerId = integerId;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }




}
